micronaut:
  application:
    name: redisson-cache-issue
redisson:
  caches:
    my-cache:
      expire-after-write: 1s
    my-cache-async:
      expire-after-write: 1s
    obj-cache-async:
      expire-after-write: 1s